front/urls.py
from django.conf.urls import url

from . import views

app_name = 'front'
urlpatterns = [
    # /builds
    url(r'^builds/$', views.BuildsView.as_view(), name='builds'),
    # /repos
    url(r'^repos/$', views.ReposView.as_view(), name='repos'),
    # builds/:id
    url(r'^builds/(?P<pk>[0-9]+)/$', views.BuildView.as_view(), name='build'),
    # /repository/:id/builds
    url(r'^repos/(?P<pk>[0-9]+)/builds/$', views.RepoBuildsView.as_view(), name='repo_builds'),
    # /
    url(r'', views.index, name='index')
]

simpleci/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^webhooks/', include('webhooks.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'', include('front.urls'))
]

webhooks/urls.py
from django.conf.urls import url
from . import views

app_name = 'webhooks'
urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^builds/(?P<build_id>[0-9]+)/rerun/$', views.rerun, name='rerun'),
    url(r'^builds/(?P<build_id>[0-9]+)/stop/$', views.stop, name='stop'),
]

front/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from json import loads
from .utils import yaml_load

@python_2_unicode_compatible
class Repo(models.Model):
    name = models.CharField(max_length=50)
    source = models.CharField(max_length=100)
    additional_setup = models.TextField(null=True, blank=True)
    slack_channel = models.CharField(max_length=20, null=True, blank=True)
    slack_token = models.CharField(max_length=100, null=True, blank=True)

    def get_commands(self):
        if self.additional_setup:
            return self.additional_setup.split('\n')
        else:
            None

    def __str__(self):
        return self.name

@python_2_unicode_compatible
class Build(models.Model):
    BUILD_STATUSES = (
        ('pending', 'pending'),
        ('running', 'running'),
        ('stopped', 'stopped'),
        ('passed', 'passed'),
        ('failed', 'failed'),
    )

    repo = models.ForeignKey(Repo, on_delete=models.CASCADE)
    branch = models.CharField(max_length=50)
    committer = models.CharField(max_length=50)
    status = models.CharField(max_length=7, choices=BUILD_STATUSES)
    log = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return "[%s] %s/%s : %s" % (self.committer, self.repo.name, self.branch, self.status)

    def get_log(self):
        print(self.log)
        return loads(self.log)

@python_2_unicode_compatible
class Pipeline(models.Model):
    repo = models.ForeignKey(Repo, on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    branch_pattern = models.CharField(max_length=50)
    commands = models.TextField()

    def get_commands(self):
        return yaml_load(self.commands)

    def __str__(self):
        return "%s (%s)" % (self.name, self.repo)

webhooks/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

front/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.shortcuts import redirect
from django.views import generic
from django.views.generic.list import ListView
from .models import Build, Repo
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required

@login_required(login_url='/admin/login/')
def index(request):
    return redirect('/repos/')

class BuildsView(LoginRequiredMixin, ListView):
    template_name = 'front/builds.html'
    context_object_name = 'builds'

    def get_queryset(self):
        return Build.objects.all()

class BuildView(LoginRequiredMixin, generic.DetailView):
    model = Build
    template_name = 'front/build.html'

class ReposView(LoginRequiredMixin, ListView):
    template_name = 'front/repos.html'
    context_object_name = 'repos'

    def get_queryset(self):
        return Repo.objects.all()

class RepoBuildsView(LoginRequiredMixin, generic.DetailView):
    # TODO: use select_related bc: N+1
    model = Repo
    template_name = 'front/repo_builds.html'

webhooks/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.shortcuts import render, get_object_or_404
from django.http import JsonResponse
from webhooks import repos
from front.models import Repo, Build
from background_task.models import Task
from django.views.decorators.csrf import csrf_exempt
from django.core.exceptions import ObjectDoesNotExist
from json import loads
from django.contrib.auth.decorators import login_required

@csrf_exempt
def index(request):
    payload = loads(request.body)

    event = request.META.get('HTTP_X_GITHUB_EVENT', 'ping')

    if event == 'push' and payload['deleted']:
        event = 'deleted'

    repo_name, branch, committer = __parse_payload(event, payload)
    repo = __get_repo(repo_name)

    if repo:
        if event == 'push':
            build = Build(repo=repo, branch=branch, committer=committer, status='pending')
            build.save()
            repos.build(build.id)
        elif event == 'pull_request':
            # TODO associate with build
            pass

    return JsonResponse({'status': 'ok'})

@login_required(login_url='/admin/login/')
def stop(request, build_id):
    build = get_object_or_404(Build, pk=build_id)
    task_params = "[[%s], {}]" %(str(build_id))
    task = get_object_or_404(Task, task_name='webhooks.repos.build', task_params=task_params)
    task.delete()
    build.status = 'stopped'
    build.save()
    return render(request, 'webhooks/stop.html', {'build': build})

@login_required(login_url='/admin/login/')
def rerun(request, build_id):
    build = get_object_or_404(Build, pk=build_id)
    build.status = 'running'
    build.save()
    repos.build(build.id)
    return render(request, 'webhooks/rerun.html', {'build': build})

def __parse_payload(event, payload):
    repo = payload['repository']['name'] if 'repository' in payload else None
    branch = None
    committer = None

    try:
        if 'ref_type' in payload:
            if payload['ref_type'] == 'branch':
                branch = payload['ref']
        elif 'pull_request' in payload:
            branch = payload['pull_request']['base']['ref']
        elif event in ['push']:
            branch = payload['ref'].split('/', 2)[2]
            committer = payload['pusher']['name']
    except KeyError:
        pass

    return [repo, branch, committer]

def __get_repo(name):
    try:
        return Repo.objects.get(name=name)
    except ObjectDoesNotExist:
        return None

front/templates/front/base.html
{% load staticfiles %}
<html>
    <head>
        <title>SiHayBuild!</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
        <script src="https://code.jquery.com/jquery-3.1.1.slim.min.js" integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>
    </head>
    <body>
      {% block content %}{% endblock %}
    </body>
</html>

front/templates/front/build.html
{% extends 'front/base.html' %}
{% block content %}
  <h1>Build</h1>

  <ul class="list-group">
    <li class="list-group-item"><b>Repo: </b> {{ build.repo }}</li>
    <li class="list-group-item"><b>Branch: </b> {{ build.branch }}</li>
    <li class="list-group-item"><b>Commiter: </b> {{ build.committer }}</li>
    <li class="list-group-item"><b>Status: </b> {{ build.status }}</li>
    <li class="list-group-item">
      {% for stage in build.get_log %}
        <div>
          <strong>{{stage.stage}}</strong>
          <br />
          <ol>
            {% for cmd in stage.log %}
              <li>
                {{cmd.command}}
                <br/ >
                {{cmd.output}}
              </li>
            {% endfor %}
          </ol>
        </div>
      {% endfor %}
     </li>
  </ul>

  <p><a href="{% url 'front:repo_builds' build.repo.id %}">Back to repo</a></p>
{% endblock %}

front/templates/front/builds.html
{% extends 'front/base.html' %}
{% block content %}
  <h1>Builds:</h1>

  <ul>
    {% for build in builds %}
      <li>
        {{ build }}
      </li>
    {% endfor %}
  </ul>
{% endblock %}

front/templates/front/repo_builds.html
{% extends 'front/base.html' %}
{% block content %}
  <h1>Builds: {{ repo.name }}</h1>

  <ul>
    {% for build in repo.build_set.all %}
      <li>
        {{ build }} ->
        <a href="{% url 'front:build' build.id %}">Show</a> -->
        {% if build.status == 'running' %}
          <a href="{% url 'webhooks:stop' build.id %}">Stop</a>
        {% else %}
          <a href="{% url 'webhooks:rerun' build.id %}">Rerun</a>
        {% endif %}
      </li>
    {% endfor %}
  </ul>

  <a href="{% url 'front:repos' %}">Back to repos</a>
{% endblock %}

front/templates/front/repos.html
{% extends 'front/base.html' %}
{% block content %}
  <h1>Repos:</h1>

  <ul>
    {% for repo in repos %}
      <li>
        <b>{{ repo }}</b> <a href="{% url 'front:repo_builds' repo.id %}">builds</a>
      </li>
    {% endfor %}
  </ul>
{% endblock %}

webhooks/templates/webhooks/rerun.html
{% extends 'front/base.html' %}
{% block content %}
  <h1>Reruning build....</h1>
  <h2><a href="{% url 'front:repo_builds' build.repo_id %}">Back to builds</a></h2>
{% endblock %}

webhooks/templates/webhooks/stop.html
{% extends 'front/base.html' %}
{% block content %}
  <h1>Build stopped</h1>

  <a href="{% url 'front:repo_builds' build.repo_id %}">Back to builds</a>
{% endblock %}